### ISSUE TITLE
App Crashes When Opting in

### ISSUE THREAD

**Issue by plamenGo** [xamarin/xamarin.exposurenotification#25]
Hey guys,

App crashes for me when install on my fully updated iOS 13.5. I have Xcode Version 11.5 beta (11N605c), and have it selected under SDK manager in my Visual Studio. Do you have any advice for me, or can I provide any more info?

Thank you!

> Error Domain=NSOSStatusErrorDomain Code=-71148 "kInvalidatedErr (XPC connection invalidated)" UserInfo={NSLocalizedDescription=kInvalidatedErr (XPC connection invalidated), cuErrorDesc=kInvalidatedErr (XPC connection invalidated), cuErrorMsg=XPC connection invalidated}

**Comment by plamenGo** [comment]
I just double checked my iphone setting and is says -- "Not available in your country", what the heck! I am in the US! Should this work for me?

**Comment by Redth** [comment]
You need to apply to Apple and Google to use the API's in an app:

Apple: https://developer.apple.com/contact/request/exposure-notification-entitlement
Google: https://support.google.com/googleplay/android-developer/contact/expo_notif_api

In the case of apple, your provisioning profile needs to have the correct entitlement in order to use the API at runtime.
