### ISSUE TITLE
Add the ability to adjust bgRepeatInterval on Android

### ISSUE THREAD

**Issue by havart-netcompany** [xamarin/xamarin.exposurenotification#43]
Calling Init() does PlatformScheduleFetch(), which schedules a periodic work request on Android. Currently, the repeat interval is 6 hours (bgRepeatInterval). We would like to change the repeat interval. There is a function called ConfigureBackgroundWorkRequest(), but it is not referenced anywhere and it's not accessible to the app using the cross-platform library. Is the existence of this function a sign that the ability to change bgRequestBuilder and bgRepeatInterval will be added soon?

**Comment by Redth** [comment]
You will need to access this from the Android app head project.  I'd put it in your MainActivity.cs file, something like this:

```csharp
Xamarin.ExposureNotifications.ExposureNotification.ConfigureBackgroundWorkRequest(TimeSpan.FromHours(12), b =>
{
	b.SetPeriodStartTime(TimeSpan.FromSeconds(1))
	.SetConstraints(new AndroidX.Work.Constraints.Builder()
		.SetRequiredNetworkType(AndroidX.Work.NetworkType.Connected)
		.SetRequiresCharging(true)
		.Build());
});
```

This will cause the builder you set, to be used instead of the default one:
-  https://github.com/xamarin/xamarin.exposurenotification/blob/master/Xamarin.ExposureNotification/ExposureNotification.android.cs#L125-L126
 - https://github.com/xamarin/xamarin.exposurenotification/blob/master/Xamarin.ExposureNotification/ExposureNotification.android.cs#L144-L146

When the fetch is scheduled during the Init call: https://github.com/xamarin/xamarin.exposurenotification/blob/master/Xamarin.ExposureNotification/ExposureNotification.shared.cs#L60

**Comment by Redth** [comment]
@havart-netcompany can you confirm this provides you with what you need?

**Comment by havart-netcompany** [comment]
@Redth I can confirm that your suggestion provides me with what I need
