### ISSUE TITLE
Any plans get and confirm phone numbers from users?

### ISSUE THREAD

**Issue by plamenGo** [xamarin/xamarin.exposurenotification#6]
Are there any plans to prompt the user to enter their phone number and otp?

That's how TraceTogether works, and it gives the local authority more possibilities when deciding on their protocol. IE they can call potentially infected people or send them texts, instead of just hoping they check the app or respond to push notifications. 

I understand that takes away from users' privacy and that's an argument against doing this.

**Comment by Redth** [comment]
Sorry, but no, there are no plans for this.  It's been made pretty clear by the specs from both companies that this data should not in any way link personally identifiable information with the Temporary Exposure Keys.  The idea is that there's no need to send texts because the app will handle download and checking keys from positively diagnosed people against a local database of keys observed to anonymously inform the user of potentially exposure.
